-- Failure:  (@test-expect-condition.R#50) -------------------------------------
`object` did not throw the expected error.

-- Failure:  (@test-expect-condition.R#51) -------------------------------------
`object` threw an unexpected error.
Message: !
Class:   simpleError/error/condition
Backtrace:
    x
 1. +-testthat::expect_error(fail("!"), NA)
 2. | \-testthat::expect_condition_matching(...)
 3. |   \-testthat::quasi_capture(...)
 4. |     +-testthat:::.capture(...)
 5. |     | \-base::withCallingHandlers(...)
 6. |     \-rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
 7. \-testthat::fail("!")

-- Error:  (@test-expect-condition.R#53) ---------------------------------------
Error: xxx
Backtrace:
    x
 1. +-testthat::expect_error(fail("xxx"), "zzz")
 2. | \-testthat::expect_condition_matching(...)
 3. |   \-testthat::quasi_capture(...)
 4. |     +-testthat:::.capture(...)
 5. |     | \-base::withCallingHandlers(...)
 6. |     \-rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
 7. \-testthat::fail("xxx")

